export let role = "admin";

export const residentsData = [
  {
    id: "1",
    residentNumber: "RES001",
    fullName: "John Doe",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    dateOfBirth: "1950-05-12",
    gender: "Male",
    ethnicity: "Caucasian",
    language: "English",
    address: "123 Main St, Anytown, USA",
    contactNumber: "1234567890",
    emergencyContactName: "Jane Doe",
    emergencyContactNumber: "9876543210",
    emergencyContactRelationship: "Daughter",
    pcp: "Dr. Smith",
    pcpContact: "123-456-7890",
    dncConsent: false,
    evacuationConsent: true,
    healthConditions: "Diabetes, Hypertension",
    allergies: "Peanuts, Shellfish",
    dietaryRestrictions: "Low-sodium diet",
    insuranceProvider: "Blue Cross",
    insurancePolicyNumber: "POL12345678",
    roomNumber: "101A",
    moveInDate: "2024-01-15",
    careLevel: "Assisted",
    fallRisk: "Medium",
    assignedStaffId: "STAFF001",
    currentStatus: "Active",
    behavioralNotes: "Sometimes anxious in unfamiliar settings",
    activitiesPreferences: "Yoga, Reading, Gardening",
    createdAt: "2024-11-27T10:00:00Z",
  },
  {
    id: "2",
    residentNumber: "RES002",
    fullName: "Jane Smith",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    dateOfBirth: "1942-09-21",
    gender: "Female",
    ethnicity: "Hispanic",
    language: "Spanish",
    address: "456 Elm St, Anytown, USA",
    contactNumber: "4561237890",
    emergencyContactName: "Mark Smith",
    emergencyContactNumber: "6547893210",
    emergencyContactRelationship: "Son",
    pcp: "Dr. Garcia",
    pcpContact: "321-654-9870",
    dncConsent: true,
    evacuationConsent: false,
    healthConditions: "Arthritis, Asthma",
    allergies: "Pollen, Dust",
    dietaryRestrictions: "Gluten-free",
    insuranceProvider: "United Healthcare",
    insurancePolicyNumber: "POL87654321",
    roomNumber: "102B",
    moveInDate: "2023-09-01",
    careLevel: "Independent",
    fallRisk: "Low",
    assignedStaffId: "STAFF002",
    currentStatus: "Active",
    behavioralNotes: "Enjoys group activities, very social",
    activitiesPreferences: "Painting, Knitting, Chess",
    createdAt: "2024-11-27T10:30:00Z",
  },
  {
    id: "3",
    residentNumber: "RES003",
    fullName: "Mike Johnson",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    dateOfBirth: "1938-02-14",
    gender: "Male",
    ethnicity: "African American",
    language: "English",
    address: "789 Oak St, Anytown, USA",
    contactNumber: "7894561230",
    emergencyContactName: "Lisa Johnson",
    emergencyContactNumber: "3216549870",
    emergencyContactRelationship: "Granddaughter",
    pcp: "Dr. Brown",
    pcpContact: "789-456-1230",
    dncConsent: true,
    evacuationConsent: true,
    healthConditions: "Parkinson's disease",
    allergies: "None",
    dietaryRestrictions: "Vegetarian",
    insuranceProvider: "Medicare",
    insurancePolicyNumber: "POL11223344",
    roomNumber: "103C",
    moveInDate: "2022-06-10",
    careLevel: "Full Care",
    fallRisk: "High",
    assignedStaffId: "STAFF003",
    currentStatus: "Active",
    behavioralNotes: "Requires assistance with mobility",
    activitiesPreferences: "Watching TV, Listening to music",
    createdAt: "2024-11-27T11:00:00Z",
  },
];
