export let role = "admin";

export const residentsData = [
  {
    id: "1",
    residentNumber: "RES001",
    fullName: "John Doe",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    dateOfBirth: "1950-05-12",
    gender: "Male",
    ethnicity: "Caucasian",
    language: "English",
    address: "123 Main St, Anytown, USA",
    contactNumber: "1234567890",
    emergencyContactName: "Jane Doe",
    emergencyContactNumber: "9876543210",
    emergencyContactRelationship: "Daughter",
    pcp: "Dr. Smith",
    pcpContact: "123-456-7890",
    dncConsent: false,
    evacuationConsent: true,
    healthConditions: "Diabetes, Hypertension",
    allergies: "Peanuts, Shellfish",
    dietaryRestrictions: "Low-sodium diet",
    insuranceProvider: "Blue Cross",
    insurancePolicyNumber: "POL12345678",
    roomNumber: "101A",
    moveInDate: "2024-01-15",
    careLevel: "Assisted",
    fallRisk: "Medium",
    assignedStaffId: "STAFF001",
    currentStatus: "Active",
    behavioralNotes: "Sometimes anxious in unfamiliar settings",
    activitiesPreferences: "Yoga, Reading, Gardening",
    createdAt: "2024-11-27T10:00:00Z",
  },
  {
    id: "2",
    residentNumber: "RES002",
    fullName: "Jane Smith",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    dateOfBirth: "1942-09-21",
    gender: "Female",
    ethnicity: "Hispanic",
    language: "Spanish",
    address: "456 Elm St, Anytown, USA",
    contactNumber: "4561237890",
    emergencyContactName: "Mark Smith",
    emergencyContactNumber: "6547893210",
    emergencyContactRelationship: "Son",
    pcp: "Dr. Garcia",
    pcpContact: "321-654-9870",
    dncConsent: true,
    evacuationConsent: false,
    healthConditions: "Arthritis, Asthma",
    allergies: "Pollen, Dust",
    dietaryRestrictions: "Gluten-free",
    insuranceProvider: "United Healthcare",
    insurancePolicyNumber: "POL87654321",
    roomNumber: "102B",
    moveInDate: "2023-09-01",
    careLevel: "Independent",
    fallRisk: "Low",
    assignedStaffId: "STAFF002",
    currentStatus: "Active",
    behavioralNotes: "Enjoys group activities, very social",
    activitiesPreferences: "Painting, Knitting, Chess",
    createdAt: "2024-11-27T10:30:00Z",
  },
  {
    id: "3",
    residentNumber: "RES003",
    fullName: "Mike Johnson",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    dateOfBirth: "1938-02-14",
    gender: "Male",
    ethnicity: "African American",
    language: "English",
    address: "789 Oak St, Anytown, USA",
    contactNumber: "7894561230",
    emergencyContactName: "Lisa Johnson",
    emergencyContactNumber: "3216549870",
    emergencyContactRelationship: "Granddaughter",
    pcp: "Dr. Brown",
    pcpContact: "789-456-1230",
    dncConsent: true,
    evacuationConsent: true,
    healthConditions: "Parkinson's disease",
    allergies: "None",
    dietaryRestrictions: "Vegetarian",
    insuranceProvider: "Medicare",
    insurancePolicyNumber: "POL11223344",
    roomNumber: "103C",
    moveInDate: "2022-06-10",
    careLevel: "Full Care",
    fallRisk: "High",
    assignedStaffId: "STAFF003",
    currentStatus: "Active",
    behavioralNotes: "Requires assistance with mobility",
    activitiesPreferences: "Watching TV, Listening to music",
    createdAt: "2024-11-27T11:00:00Z",
  },
];

export const familyData = [
  {
    id: 1,
    name: "John Doe",
    residents: ["Sarah Brewer"], // List of associated residents
    email: "john@doe.com",
    phone: "1234567890",
    relationship: "Father", // New field indicating the relationship to the resident
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    name: "Jane Doe",
    residents: ["Cecilia Bradley"],
    email: "jane@doe.com",
    phone: "1234567890",
    relationship: "Mother",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    name: "Mike Geller",
    residents: ["Fanny Caldwell"],
    email: "mike@geller.com",
    phone: "1234567890",
    relationship: "Brother",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    name: "Jay French",
    residents: ["Mollie Fitzgerald", "Ian Bryant"],
    email: "jay@geller.com",
    phone: "1234567890",
    relationship: "Uncle",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    name: "Jane Smith",
    residents: ["Mable Harvey"],
    email: "jane@geller.com",
    phone: "1234567890",
    relationship: "Sister",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    name: "Anna Santiago",
    residents: ["Joel Lambert"],
    email: "anna@geller.com",
    phone: "1234567890",
    relationship: "Mother",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    name: "Allen Black",
    residents: ["Carrie Tucker", "Lilly Underwood"],
    email: "allen@geller.com",
    phone: "1234567890",
    relationship: "Father",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    name: "Ophelia Castro",
    residents: ["Alexander Blair"],
    email: "ophelia@geller.com",
    phone: "1234567890",
    relationship: "Aunt",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    name: "Derek Briggs",
    residents: ["Susan Webster", "Maude Stone"],
    email: "derek@geller.com",
    phone: "1234567890",
    relationship: "Cousin",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    name: "John Glover",
    residents: ["Stella Scott"],
    email: "john@geller.com",
    phone: "1234567890",
    relationship: "Grandfather",
    address: "123 Main St, Anytown, USA",
  },
];

export const careRecordsData = [
  {
    id: 1,
    activity: "Morning yoga session",
    resident: "John Doe",
    staff: "Alice Johnson",
    type: "activity",
    date: "2024-11-20",
    notes: "John actively participated and enjoyed the session.",
  },
  {
    id: 2,
    activity: "Medication administered",
    resident: "Jane Smith",
    staff: "Dr. Mike Geller",
    type: "incident",
    date: "2024-11-20",
    notes: "Jane missed her morning medication. Administered at 10 AM.",
  },
  {
    id: 3,
    activity: "Slip and fall in dining area",
    resident: "Robert Johnson",
    staff: "Sarah Connor",
    type: "incident",
    date: "2024-11-19",
    notes: "Robert slipped while walking. No injuries reported.",
  },
  {
    id: 4,
    activity: "Outdoor garden walk",
    resident: "Emily Davis",
    staff: "Mark Peterson",
    type: "activity",
    date: "2024-11-19",
    notes: "Emily spent 30 minutes walking and enjoying the garden.",
  },
  {
    id: 5,
    activity: "Art therapy session",
    resident: "Samuel Green",
    staff: "Laura Martinez",
    type: "activity",
    date: "2024-11-18",
    notes: "Samuel created a painting and expressed his satisfaction.",
  },
  {
    id: 6,
    activity: "Agitated behavior in common room",
    resident: "Sophia Brown",
    staff: "Anna Wilson",
    type: "incident",
    date: "2024-11-17",
    notes:
      "Sophia showed signs of agitation. Calmed down after staff intervention.",
  },
  {
    id: 7,
    activity: "Weekly physical therapy session",
    resident: "Michael Clark",
    staff: "Dr. Richard Lopez",
    type: "activity",
    date: "2024-11-16",
    notes: "Michael completed his exercises successfully.",
  },
  {
    id: 8,
    activity: "Night medication administered",
    resident: "Lucy White",
    staff: "Emily Turner",
    type: "incident",
    date: "2024-11-16",
    notes: "Night medication was administered on time.",
  },
  {
    id: 9,
    activity: "Breakfast service",
    resident: "Oliver Martinez",
    staff: "Chef Gregory",
    type: "activity",
    date: "2024-11-15",
    notes: "Oliver requested oatmeal and fruit for breakfast.",
  },
  {
    id: 10,
    activity: "Annual health check-up",
    resident: "Charlotte Hall",
    staff: "Dr. Jennifer Carter",
    type: "incident",
    date: "2024-11-15",
    notes: "Charlotte's vitals were checked. No health concerns noted.",
  },
];
